package com.techcasita.phonetic;

public interface ArtistVocab {

    String[] Tools = new String[]{"pen", "brush", "roll"};
    String[] Styles = new String[]{"emboss", "blur", "blend", "normal", "erase"};
    String[] Tasks = new String[]{"about", "explore", "publish", "share", "print", "save", "reset" };
    String[] Combinations = new String[]{"emboss pen"};

    String[] Homophones = new String[]{"there"};
    String[] Synophones = new String[]{"jeep"};


    String[] ColorNames = new String[]{
            "ALICE BLUE",
            "ANTIQUE WHITE",
            "AQUA",
            "AQUAMARINE",
            "AZURE",
            "BEIGE",
            "BISQUE",
            "BLACK",
            "BLANCHEDALMOND",
            "BLUE",
            "BLUE VIOLET",
            "BROWN",
            "BURLY WOOD",
            "CADET BLUE",
            "CHARTREUSE",
            "CHOCOLATE",
            "CORAL",
            "CORNFLOWER BLUE",
            "CORN SILK",
            "CRIMSON",
            "CYAN",
            "DARK BLUE",
            "DARK CYAN",
            "DARK GOLDENROD",
            "DARK GRAY",
            "DARK OLIVE GREEN",
            "DARK SALMON",
            "DARK TURQUOISE",
            "DIM GRAY",
            "FOREST GREEN",
            "GHOST WHITE",
            "GOLDENROD",
            "GREEN",
            "HONEYDEW",
            "INDIAN RED",
            "IVORY",
            "KHAKI",
            "LAVENDER",
            "LAVENDERBLUSH",
            "LAWN GREEN",
            "LEMON CHIFFON",
            "LIGHT BLUE",
            "LIGHT CORAL",
            "LIGHT CYAN",
            "LIGHT GOLDENROD YELLOW",
            "LIGHT GREEN",
            "LIGHT GREY",
            "LIGHT PINK",
            "LIGHT SALMON",
            "LIGHT SEA GREEN",
            "LIGHT SKY BLUE",
            "LIGHT SLATE GRAY",
            "LIGHT STEEL BLUE",
            "LIGHT YELLOW",
            "LIME",
            "LIME GREEN",
            "LINEN",
            "MAGENTA",
            "MAROON",
            "MEDIUM AQUAMARINE",
            "MEDIUM BLUE",
            "MEDIUM ORCHID",
            "MEDIUM PURPLE",
            "MEDIUM SEA GREEN",
            "MEDIUM SLATE BLUE",
            "MEDIUM SPRING GREEN",
            "MEDIUM TURQUOISE",
            "MEDIUM VIOLET RED",
            "MIDNIGHT BLUE",
            "MINTCREAM",
            "MISTY ROSE",
            "MOCCASIN",
            "NAVAJO WHITE",
            "NAVY",
            "OLD LACE",
            "OLIVE",
            "OLIVE DRAB",
            "ORANGE",
            "ORANGE RED",
            "ORCHID",
            "PALE GOLDENROD",
            "PALE GREEN",
            "PALE TURQUOISE",
            "PALE VIOLET RED",
            "PAPAYA WHIP",
            "PEACH PUFF",
            "PERU",
            "PINK",
            "PLUM",
            "POWDER BLUE",
            "PURPLE",
            "RED",
            "ROSY BROWN",
            "ROYAL BLUE",
            "SADDLE BROWN",
            "SALMON",
            "SANDY BROWN",
            "SEA GREEN",
            "SEASHELL",
            "SILVER",
            "SLATE BLUE",
            "SNOW",
            "STEEL BLUE",
            "TEAL",
            "TOMATO",
            "VIOLET",
            "WHITE",
            "YELLOW"};
}



